version: '3'

networks:
  tfeo-network:

services:
  tfeo-mysql:
    container_name: "mysql"
    image: mysql:8.0.32
    networks:
      - tfeo-network
    ports:
      - "3306:3306"
    env_file:
      - docker-db.env
    environment:
      TZ: Asia/Seoul
    volumes:
      - /home/ubuntu/jenkins-data/workspace/jenkins_pipeline/exec/docker/initial-mysql:/docker-entrypoint-initdb.d
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    restart: "no"

  tfeo-redis:
    container_name: "redis"
    image: redis:latest
    networks:
      - tfeo-network
    ports:
      - "6379:6379"
    environment:
      TZ: Asia/Seoul
    volumes:
      - /home/ubuntu/jenkins-data/workspace/jenkins_pipeline/exec/docker/tfeo-redis/data:/data
      - /home/ubuntu/jenkins-data/workspace/jenkins_pipeline/exec/docker/tfeo-redis/conf:/etc/redis/redis.conf
    restart: "no"

  tfeo-mongodb:
    image: mongo:5.0.25
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - /home/ubuntu/jenkins-data/workspace/jenkins_pipeline/exec/docker/initial-mongo:/docker-entrypoint-initdb.d
    environment:
      - docker-db.env

#  tfeo-back:
#    container_name: "back"
#    build:
#      dockerfile: "dockerfile"
#      context: "../../backend"
#    image: tfeo-back-image
#    networks:
#      - tfeo-network
#    ports:
#      - "8081:8081"
#    env_file:
#      - tfeo-back/env/db.env
#      - tfeo-back/env/test-db.env
#      - tfeo-back/env/security.env
#    environment:
#      TZ: Asia/Seoul
#    depends_on:
#      - tfeo-mysql
#      - tfeo-redis
#    restart: "no"

#  tfro-front:
#    container_name: "front"
#    build:
#      dockerfile: "dockerfile"
#      context: "../../frontend"
#    image: tfeo-front-image
#    networks:
#      - tfeo-network
#    ports:
#      - "3000:3000"
#    environment:
#      TZ: Asia/Seoul
#    restart: "no"

  tfeo-nginx:
    container_name: "nginx"
    image: nginx:1.18.0
    volumes:
      - /home/ubuntu/jenkins-data/workspace/jenkins_pipeline/exec/docker/tfeo-nginx/conf:/etc/nginx/conf.d
      - /home/ubuntu/homeImage:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    networks:
      - tfeo-network
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - tfeo-mysql
      - tfeo-redis

    restart: always



