spring:
  config:
    import:
      - optional:file:env/security.env[.properties]
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
coolsms:
  api:
    key: ${COOLSMS_API_KEY}
    secret: ${COOLSMS_API_SECRET_KEY}